M48
; DRILL file KiCad 10.0.2 date 2026-05-26T13:51:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-26T13:51:13+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X98.25Y-74.75
X98.25Y-144.75
X228.25Y-74.75
X228.25Y-144.75
M30
